[project]
name = 'Synthetic-Media-Detection-and-Verification-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.content-moderation]
path = 'contracts/content-moderation.clar'
clarity_version = 2
epoch = 2.5

[contracts.incentive-token]
path = 'contracts/incentive-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.media-analysis_]
path = 'contracts/media-analysis_.clar'
clarity_version = 2
epoch = 2.5

[contracts.platform-integration]
path = 'contracts/platform-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
